<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (Category $category) {
            if (is_null($category->parent_id)) {
                $category->level = 0;
                $category->path = '-';
            } else {
                $category->level = $category->parent->level + 1;
                $category->path = $category->parent->path . $category->parent_id . '-';
            }
        });
    }

    public function parent()
    {
        return $this->belongsTo(category::class);
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public static function categoryTree($categories = null, $parent_id = null)
    {
        if (is_null($categories)) {
            $categories = Category::query()->get();
        }

        $categoryData = $categories->where('parent_id', $parent_id)->map(function (Category $category) use ($categories) {
            $data = ['id' => $category->id, 'name' => $category->name];
            if (!$category->is_directory) {
                return $data;
            }
            $data['children'] = self::categoryTree($categories, $category->id);
            return $data;
        });

        return $categoryData;
    }
    #拆分path
    public function getPathIdsAttribute()
    {
        return array_filter(explode('-',trim($this->path,'-')));
    }

    #获取当前数据的所有上级id
    public function getAncestorAttribute($value)
    {
        return Category::query()->where('id',$this->pathIds)->orderBy('level')->get();
    }

    public function getFullNameAttribute()
    {
        if($this->path === '-'){
            return $this->name;
        }
        return $this->ancestor
            ->pluck('name')
            ->push($this->name)
            ->implode('-');
    }
}
